on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7', '2.7']
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: constructor-env
          auto-update-conda: true
          condarc-file: etc/condarc.yml
          environment-file: etc/environment.yml
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run: |
          pip install git+git://github.com/conda/constructor@5c9539a95ed7eafb#egg=constructor --force --no-deps
          conda info
          conda list
      - name: Set Environment
        shell: bash -l {0}
        run: |
          export PYVER=${{ matrix.python-version }}
          echo "::set-env name=COMMANDERCONDA_NAME::CommanderConda${PYVER%%.*}"
      - name: Build conda distribution
        shell: bash -l {0}
        run: |
          echo "COMMANDERCONDA_NAME = ${COMMANDER_CONDA}"
          constructor --verbose --test || true
          constructor --verbose --dry-run ./CommanderConda || true
          constructor --verbose ./CommanderConda
