on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7', '2.7']
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: constructor-env
          auto-update-conda: true
          condarc-file: etc/condarc.yml
          environment-file: etc/environment.yml
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run: |
          echo "GITHUB_EVENT_NAME = ${GITHUB_EVENT_NAME}"
          echo "GITHUB_REF = ${GITHUB_REF}"
          pip install git+git://github.com/conda/constructor@5c9539a95ed7eafb#egg=constructor --force --no-deps
          conda info
          conda list
      - name: Set Environment
        shell: bash -l {0}
        run: |
          export PYVER=${{ matrix.python-version }}
          echo "::set-env name=COMMANDERCONDA_NAME::CommanderConda${PYVER%%.*}"
      - name: Build conda distribution
        id: bcd
        shell: bash -l {0}
        run: |
          echo "COMMANDERCONDA_NAME = ${COMMANDERCONDA_NAME}"
          constructor --verbose --test || true
          constructor --verbose --dry-run ./CommanderConda || true
          constructor --verbose ./CommanderConda
          ls -Gla
          export CCFILE="$(echo CommanderConda*-*)"
          du -h "${CCFILE}"
          echo "::set-env name=CCFILE::${CCFILE}"
          echo "::set-output name=ccfile::${CCFILE}"
      - name: Create checksum file
        id: get-files
        env:
          SHA256: ${{ hashFiles( steps.bcd.outputs.ccfile ) }}
        shell: bash -l {0}
        run: |
          echo "${SHA256}  ${CCFILE}" | tee "${CCFILE}.sha256"
          if ! [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            if ! shasum -c "${CCFILE}.sha256" ; then
              rm "${CCFILE}.sha256"
              if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
                shasum -b -a 256 "${CCFILE}" | tee "${CCFILE}.sha256"
              else
                sha256sum -b "${CCFILE}" | tee "${CCFILE}.sha256"
              fi
            fi
            shasum -c -w "${CCFILE}.sha256"
          fi
          zip -v "${CCFILE%.*}.zip" "${CCFILE}" "${CCFILE}.sha256"
          ls -Gla
          echo "::set-output name=asset::${CCFILE%.*}.zip"
      - name: Test distribution
        if: contains( matrix.os, 'ubuntu' ) || contains( matrix.os, 'macos' )
        env:
          SHA256: ${{ hashFiles( steps.bcd.outputs.ccfile ) }}
        shell: bash
        run: |
          ./${CCFILE} -h || true
          ./${CCFILE} -b -f
          ./${CCFILE} -b -f -t || true
          if ! [[ "${GITHUB_REF## }" =~ "^refs/tags/" ]]; then ./${CCFILE} -b -u -t ; fi
      - name: upload
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}-${{ matrix.python-version }}-asset
          path: ${{ steps.get-files.outputs.asset }}
