on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: [github-pr-review,github-check]
          exclude: "./.git/*"
      - uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: [github-pr-review,github-check]
          locale: "US"
